[2024-08-07 16:39:15] Worksheet: Michael Tenney, Job Board: Indeed
Traceback (most recent call last):
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 102, in main
    processed_jobs_last_30_days = retrieve_processed_job_data_from_mysql(candidate_id, connection)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\DB_ops.py", line 59, in retrieve_processed_job_data_from_mysql
    cursor = connection.cursor(cursorclass=DictCursor)  # For localhost
             ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'


[2024-08-07 16:39:38] Worksheet: Ryan Mattonen, Job Board: Indeed
Traceback (most recent call last):
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 102, in main
    processed_jobs_last_30_days = retrieve_processed_job_data_from_mysql(candidate_id, connection)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\DB_ops.py", line 59, in retrieve_processed_job_data_from_mysql
    cursor = connection.cursor(cursorclass=DictCursor)  # For localhost
             ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'


[2024-08-07 16:39:57] Worksheet: Joao Priori, Job Board: Indeed
Traceback (most recent call last):
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 102, in main
    processed_jobs_last_30_days = retrieve_processed_job_data_from_mysql(candidate_id, connection)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\DB_ops.py", line 59, in retrieve_processed_job_data_from_mysql
    cursor = connection.cursor(cursorclass=DictCursor)  # For localhost
             ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'


[2024-08-07 16:40:10] Worksheet: Robert Brightwell, Job Board: Indeed
Traceback (most recent call last):
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 102, in main
    processed_jobs_last_30_days = retrieve_processed_job_data_from_mysql(candidate_id, connection)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\DB_ops.py", line 59, in retrieve_processed_job_data_from_mysql
    cursor = connection.cursor(cursorclass=DictCursor)  # For localhost
             ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'


[2024-08-07 16:40:16] Worksheet: Carla Taylor, Job Board: Indeed
Traceback (most recent call last):
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 102, in main
    processed_jobs_last_30_days = retrieve_processed_job_data_from_mysql(candidate_id, connection)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\DB_ops.py", line 59, in retrieve_processed_job_data_from_mysql
    cursor = connection.cursor(cursorclass=DictCursor)  # For localhost
             ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'


[2024-08-07 16:42:09] Worksheet: test, Job Board: Indeed
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1395, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 325, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 286, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 106, in main
    get_job_data(base_url, worksheet_name, driver, candidate_id, connection, client_requirements, processed_jobs_last_30_days)
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 31, in get_job_data
    driver.get(base_url)
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 363, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 352, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\remote_connection.py", line 302, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\remote_connection.py", line 322, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\_request_methods.py", line 144, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\_request_methods.py", line 279, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1397, in getresponse
    self.close()
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\urllib3\connection.py", line 273, in close
    def close(self) -> None:
    
KeyboardInterrupt


[2024-08-07 16:42:20] Worksheet: test, Job Board: Indeed
Traceback (most recent call last):
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 111, in main
    write_job_data_to_google_sheet(jobs_data, worksheet_name, is_remote)
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\sheet_ops.py", line 91, in write_job_data_to_google_sheet
    worksheet.update(range_name=cell_range, values=rows_to_update, value_input_option='USER_ENTERED')
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gspread\worksheet.py", line 1240, in update
    response = self.client.values_update(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gspread\http_client.py", line 173, in values_update
    r = self.request("put", url, params=params, json=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gspread\http_client.py", line 128, in request
    raise APIError(response)
gspread.exceptions.APIError: APIError: [400]: Unable to parse range: 'test'!A1:H0


[2024-08-07 16:45:16] Worksheet: test, Job Board: Indeed
Traceback (most recent call last):
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 107, in main
    get_job_data(base_url, worksheet_name, driver, candidate_id, connection, client_requirements, processed_jobs_last_30_days)
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 31, in get_job_data
    driver.get(base_url)
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 363, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=127.0.6533.89)
Stacktrace:
	GetHandleVerifier [0x00007FF62C939632+30946]
	(No symbol) [0x00007FF62C8EE3C9]
	(No symbol) [0x00007FF62C7E6FDA]
	(No symbol) [0x00007FF62C7BCB85]
	(No symbol) [0x00007FF62C8637A7]
	(No symbol) [0x00007FF62C87A771]
	(No symbol) [0x00007FF62C85C813]
	(No symbol) [0x00007FF62C82A6E5]
	(No symbol) [0x00007FF62C82B021]
	GetHandleVerifier [0x00007FF62CA6F83D+1301229]
	GetHandleVerifier [0x00007FF62CA7BDB7+1351783]
	GetHandleVerifier [0x00007FF62CA72A03+1313971]
	GetHandleVerifier [0x00007FF62C96DD06+245686]
	(No symbol) [0x00007FF62C8F758F]
	(No symbol) [0x00007FF62C8F3804]
	(No symbol) [0x00007FF62C8F3992]
	(No symbol) [0x00007FF62C8EA3EF]
	BaseThreadInitThunk [0x00007FFF230B7374+20]
	RtlUserThreadStart [0x00007FFF231FCC91+33]



[2024-08-07 16:45:19] Worksheet: test, Job Board: Indeed
Traceback (most recent call last):
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\indeed.py", line 112, in main
    write_job_data_to_google_sheet(jobs_data, worksheet_name, is_remote)
  File "c:\Users\Ahtsham\Downloads\Indeed scraping\Indeed scraping\sheet_ops.py", line 91, in write_job_data_to_google_sheet
    worksheet.update(range_name=cell_range, values=rows_to_update, value_input_option='USER_ENTERED')
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gspread\worksheet.py", line 1240, in update
    response = self.client.values_update(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gspread\http_client.py", line 173, in values_update
    r = self.request("put", url, params=params, json=body)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ahtsham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gspread\http_client.py", line 128, in request
    raise APIError(response)
gspread.exceptions.APIError: APIError: [400]: Unable to parse range: 'test'!A1:H0


